import { useEffect, useRef, useState } from 'react';
import type { Lesson } from '../../types';
import { updateProgress } from '../../utils/progress';
import { completeDailyTask } from '../../utils/dailyTasks';

type Result = { total:number; duration:number; words:number; keywords:number; fluency:number; transcript:string; passed:boolean };
type SpeechRecognitionLike = { continuous:boolean; interimResults:boolean; lang:string; onresult:((event:any)=>void)|null; onerror:((event:any)=>void)|null; start:()=>void; stop:()=>void };

export function SpeakingRecorder({ lesson }: { lesson: Lesson }) {
  const recorder=useRef<MediaRecorder|null>(null); const recognition=useRef<SpeechRecognitionLike|null>(null); const chunks=useRef<Blob[]>([]); const timer=useRef<number|null>(null); const transcriptRef=useRef(''); const secondsRef=useRef(0);
  const [recording,setRecording]=useState(false); const [seconds,setSeconds]=useState(0); const [audioUrl,setAudioUrl]=useState(''); const [error,setError]=useState(''); const [result,setResult]=useState<Result|null>(null);
  const [rewards,setRewards]=useState(()=>({xp:Number(localStorage.getItem('lingua:xp')||0),coins:Number(localStorage.getItem('lingua:coins')||0)}));
  useEffect(()=>()=>{if(timer.current)clearInterval(timer.current);if(audioUrl)URL.revokeObjectURL(audioUrl)},[audioUrl]);

  const score=(durationSeconds:number,transcript:string):Result=>{const words=transcript.toLowerCase().match(/[a-z]+(?:'[a-z]+)?/g)||[];const targets=lesson.vocabulary.map(v=>v.word.toLowerCase()).filter(w=>w.split(' ').length<=3);const hits=targets.filter(k=>transcript.toLowerCase().includes(k)).length;const durationScore=Math.min(25,Math.round(durationSeconds/60*25));const wordScore=Math.min(25,Math.round(words.length/80*25));const keywordScore=Math.min(25,Math.round(hits/Math.min(5,Math.max(1,targets.length))*25));const wpm=durationSeconds?words.length/(durationSeconds/60):0;const fluencyScore=words.length<10?0:Math.max(5,Math.min(25,Math.round(25-Math.abs(wpm-105)/5)));const total=durationScore+wordScore+keywordScore+fluencyScore;return{total,duration:durationScore,words:wordScore,keywords:keywordScore,fluency:fluencyScore,transcript,passed:total>=60}};
  const grantReward=(final:Result)=>{updateProgress(lesson.id,{speakingScore:final.total});if(final.passed)completeDailyTask('speaking');if(!final.passed)return;const key=`lingua:reward:${lesson.id}`;if(localStorage.getItem(key))return;const xp=rewards.xp+final.total;const coins=rewards.coins+10;localStorage.setItem(key,'1');localStorage.setItem('lingua:xp',String(xp));localStorage.setItem('lingua:coins',String(coins));localStorage.setItem(`speaking:${lesson.id}`,'completed');setRewards({xp,coins})};
  const start=async()=>{try{setError('');setResult(null);transcriptRef.current='';secondsRef.current=0;const stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks.current=[];const next=new MediaRecorder(stream);recorder.current=next;next.ondataavailable=e=>chunks.current.push(e.data);next.onstop=()=>{const url=URL.createObjectURL(new Blob(chunks.current,{type:next.mimeType}));setAudioUrl(url);stream.getTracks().forEach(t=>t.stop());const final=score(secondsRef.current,transcriptRef.current);setResult(final);grantReward(final)};const Recognition=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(Recognition){const sr:SpeechRecognitionLike=new Recognition();sr.continuous=true;sr.interimResults=true;sr.lang='en-US';sr.onresult=(event:any)=>{let text='';for(let i=0;i<event.results.length;i++)text+=event.results[i][0].transcript+' ';transcriptRef.current=text.trim()};sr.onerror=()=>setError('语音转文字暂时中断，仍会保留录音并进行基础评分。');sr.start();recognition.current=sr}else setError('当前浏览器不支持英文语音识别，建议使用 Chrome 获得完整评分。');next.start();setSeconds(0);setRecording(true);timer.current=window.setInterval(()=>setSeconds(v=>{secondsRef.current=v+1;return v+1}),1000)}catch{setError('无法使用麦克风，请在浏览器地址栏允许麦克风权限。')}};
  const stop=()=>{recognition.current?.stop();recorder.current?.stop();setRecording(false);if(timer.current)clearInterval(timer.current)};
  const level=Math.floor(rewards.xp/300)+1;
  return <section className="speaking-recorder"><div className="reward-bar"><span>Level {level}</span><span>{rewards.xp} XP</span><span>{rewards.coins} coins</span></div><p className="card-kicker">SPEAKING CHALLENGE</p><h3>60 分过关，完成独立回答</h3><p>目标：连续表达 60–120 秒，并主动使用本课重点词汇。</p><div className="recording-controls">{!recording?<button className="record-btn" onClick={start}>{audioUrl?'重新挑战':'开始挑战'}</button>:<button className="record-btn recording" onClick={stop}>停止并评分 · {seconds}s</button>}{audioUrl&&<audio src={audioUrl} controls/>}</div>{error&&<p className="record-error">{error}</p>}{result&&<div className={`score-panel ${result.passed?'passed':'failed'}`}><div className="score-total"><strong>{result.total}</strong><span>/ 100</span><b>{result.passed?'闯关成功 +10 coins':'尚未过关，再试一次'}</b></div><div className="score-breakdown"><span>时长 {result.duration}/25</span><span>有效词数 {result.words}/25</span><span>重点词汇 {result.keywords}/25</span><span>连续表达 {result.fluency}/25</span></div>{result.transcript&&<details><summary>查看识别文本</summary><p>{result.transcript}</p></details>}</div>}<p className="privacy-note">评分是练习反馈，不等同于 IELTS 官方分数；录音不会上传。</p></section>;
}
